#ifndef FREE_PROJECT_DUNGEON_CONSTANTS_H
#define FREE_PROJECT_DUNGEON_CONSTANTS_H

#define BG_OFFSET_X 0
#define BG_OFFSET_Y 8

#define UI_PLAYER_X 21
#define UI_PLAYER_Y 16

#define UI_LIFEBAR_BG_X 92
#define UI_LIFEBAR_BG_Y 20
#define UI_LIFEBAR_X 95
#define UI_LIFEBAR_Y 23
#define UI_LIFEBAR_W 217
#define UI_LIFEBAR_H 34

#define UI_MAP_BG_X 1096
#define UI_MAP_BG_Y 16


#endif //FREE_PROJECT_DUNGEON_CONSTANTS_H
